FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update
#RUN yes | unminimize
RUN apt-get install -yq \
    build-essential \
    git \
    liblzma-dev

RUN cd / && git clone https://github.com/ipxe/ipxe.git
RUN cd ipxe/src && make \
    bin-x86_64-pcbios/ipxe.pxe \
    bin-x86_64-pcbios/undionly.kpxe \
    bin-x86_64-efi/ipxe.efi
